#!/bin/sh

dryrun=NO
if [ $1 = '-n' ]; then
    dryrun=YES
    shift
fi

PREFIX=${1:-/usr/local/folio}
DIRS="bin conf"
PERLMODDIR=$(awk '/^PERLMODDIR  *=  */ {print $3}' config.mk)
if [ -n "$PERLMODDIR" ]; then
    DIRS="${DIRS} ${PERLMODDIR}"
fi

for dir in $DIRS; do
    if [ -e $dir ]; then
        if [ $dryrun = YES ]; then
            echo "mkdir -p $PREFIX/$dir" >&2
            echo "rsync -av $dir/ $PREFIX/$dir/"
            if [ -e $PREFIX/$dir/ ]; then
                rsync -av --dry-run $dir/ $PREFIX/$dir/
            else
                rsync -av --dry-run $dir/ /tmp/
            fi
        else
            mkdir -p $PREFIX/$dir
            rsync -av $dir/ $PREFIX/$dir/
        fi
    fi
done

chmod a+x $PREFIX/bin/
