#!/bin/sh

dryrun=NO
if [ $1 = '-n' ]; then
    dryrun=YES
    shift
fi

PREFIX=${1:-/usr/local/folio}
DIRS="bin conf"
PERLMOD=$(awk '/^PERLMOD  *=  */ {print $3}' config.mk)
PERLMODPAR=$(awk '/^PERLMODPAR  *=  */ {print $3}' config.mk)
PERLMODDIR=$(awk '/^PERLMODDIR  *=  */ {print $3}' config.mk)
if [ -n "$PERLMODDIR" ]; then
    DIRS="${DIRS} ${PERLMODDIR}"
fi

for dir in $DIRS; do
    if [ -e $dir ]; then
        if [ $dryrun = YES ]; then
            echo "mkdir -p $PREFIX/$dir" >&2
            echo "rsync -av $dir/ $PREFIX/$dir/" >&2
        else
            mkdir -p $PREFIX/$dir
            rsync -av $dir/ $PREFIX/$dir/
        fi
    fi
done

if [ -n "$PERLMOD" ]; then
    if [ $dryrun = YES ]; then
        echo "cp $PERLMOD $PREFIX/$PERLMODPAR" >&2
    else
        cp $PERLMOD $PREFIX/$PERLMODPAR
    fi
fi

chmod a+x $PREFIX/bin/
